name: birdcar
favicon: null
layout_spectrum: 0.75941
typography_spectrum: 0.50313
title: A Grid for Birdcar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d3557'
    - '#f1faee'
    - '#e63946'
    - '#457b9d'
    - '#a3a5a6'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
