name: birdcar
favicon: null
layout_spectrum: 0.24763
typography_spectrum: 0.36451
title: A Grid for Birdcar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d3557'
    - '#f1faee'
    - '#e63946'
    - '#457b9d'
    - '#a3a5a6'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
