name: birdcar
favicon: null
layout_spectrum: 0.24763
typography_spectrum: 0.36451
title: A Grid for Birdcar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#494949'
    - '#ff5d73'
    - '#ffffff'
    - '#000000'
    - '#7c7a7a'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
